# Generated by Django 5.2.3 on 2025-07-01 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='current_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
